name: github-pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    name: build-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm ci
      - name: Run tests
        run: npm test
      - name: Build pages
        run: npm run build:docs
        env:
          GITHUB_PAGES: true
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./docs
  deploy:
    name: deploy-pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v5
